version: "3"

services:
  db:
    image: postgres:14
    restart: always
    ports: 
      - "5432:5432"
    env_file: .env

  backend:
    image: node:18.4.0-alpine
    ports: 
      - "8080:8080"
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
